# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.srcs/sources_1/bd/data_mobility/ip/data_mobility_axi_dma_2_4_1/data_mobility_axi_dma_2_4.xci
# IP: The module: 'data_mobility_axi_dma_2_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/data_mobility/ip/data_mobility_axi_dma_2_4_1/data_mobility_axi_dma_2_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mobility_axi_dma_2_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/data_mobility/ip/data_mobility_axi_dma_2_4_1/data_mobility_axi_dma_2_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mobility_axi_dma_2_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/data_mobility/ip/data_mobility_axi_dma_2_4_1/data_mobility_axi_dma_2_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mobility_axi_dma_2_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.srcs/sources_1/bd/data_mobility/ip/data_mobility_axi_dma_2_4_1/data_mobility_axi_dma_2_4.xci
# IP: The module: 'data_mobility_axi_dma_2_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/data_mobility/ip/data_mobility_axi_dma_2_4_1/data_mobility_axi_dma_2_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mobility_axi_dma_2_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/data_mobility/ip/data_mobility_axi_dma_2_4_1/data_mobility_axi_dma_2_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mobility_axi_dma_2_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/data_mobility/ip/data_mobility_axi_dma_2_4_1/data_mobility_axi_dma_2_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mobility_axi_dma_2_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
