# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.srcs/sources_1/bd/dma/ip/dma_axis_data_fifo_0_2/dma_axis_data_fifo_0_2.xci
# IP: The module: 'dma_axis_data_fifo_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axis_data_fifo_0_2/dma_axis_data_fifo_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_data_fifo_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.srcs/sources_1/bd/dma/ip/dma_axis_data_fifo_0_2/dma_axis_data_fifo_0_2.xci
# IP: The module: 'dma_axis_data_fifo_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axis_data_fifo_0_2/dma_axis_data_fifo_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_data_fifo_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
