# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Test_1/Test_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1 || ORIG_REF_NAME==Test_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_DataBufferAxi_0_0/Test_1_DataBufferAxi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_DataBufferAxi_0_0 || ORIG_REF_NAME==Test_1_DataBufferAxi_0_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_al_ultra96v2_0_0/Test_1_al_ultra96v2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_al_ultra96v2_0_0 || ORIG_REF_NAME==Test_1_al_ultra96v2_0_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_0_0/Test_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_0_0 || ORIG_REF_NAME==Test_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_1_0/Test_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_1_0 || ORIG_REF_NAME==Test_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_10_0/Test_1_axi_gpio_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_10_0 || ORIG_REF_NAME==Test_1_axi_gpio_10_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_2_0/Test_1_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_2_0 || ORIG_REF_NAME==Test_1_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_3_0/Test_1_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_3_0 || ORIG_REF_NAME==Test_1_axi_gpio_3_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_4_0/Test_1_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_4_0 || ORIG_REF_NAME==Test_1_axi_gpio_4_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_5_0/Test_1_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_5_0 || ORIG_REF_NAME==Test_1_axi_gpio_5_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_7_0/Test_1_axi_gpio_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_7_0 || ORIG_REF_NAME==Test_1_axi_gpio_7_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_8_0/Test_1_axi_gpio_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_8_0 || ORIG_REF_NAME==Test_1_axi_gpio_8_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_9_0/Test_1_axi_gpio_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_9_0 || ORIG_REF_NAME==Test_1_axi_gpio_9_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_ila_0_0/Test_1_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_ila_0_0 || ORIG_REF_NAME==Test_1_ila_0_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_xbar_0/Test_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_xbar_0 || ORIG_REF_NAME==Test_1_xbar_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_auto_ds_0/Test_1_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_auto_ds_0 || ORIG_REF_NAME==Test_1_auto_ds_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_auto_pc_0/Test_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_auto_pc_0 || ORIG_REF_NAME==Test_1_auto_pc_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_auto_ds_1/Test_1_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_auto_ds_1 || ORIG_REF_NAME==Test_1_auto_ds_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_auto_pc_1/Test_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_auto_pc_1 || ORIG_REF_NAME==Test_1_auto_pc_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_ps8_0_axi_periph_0/Test_1_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==Test_1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_rst_ps8_0_99M_0/Test_1_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==Test_1_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_xlconstant_0_0/Test_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_xlconstant_0_0 || ORIG_REF_NAME==Test_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_xlconstant_3_0/Test_1_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_xlconstant_3_0 || ORIG_REF_NAME==Test_1_xlconstant_3_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_zynq_ultra_ps_e_0_0/Test_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Test_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_pulse_generator_1_0/Test_1_pulse_generator_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_pulse_generator_1_0 || ORIG_REF_NAME==Test_1_pulse_generator_1_0} -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Test_1/Test_1_ooc.xdc
