# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.srcs/sources_1/bd/Test_2/ip/Test_2_auto_ds_0/Test_2_auto_ds_0.xci
# IP: The module: 'Test_2_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test_2/ip/Test_2_auto_ds_0/Test_2_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_2_auto_ds_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test_2/ip/Test_2_auto_ds_0/Test_2_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_2_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.srcs/sources_1/bd/Test_2/ip/Test_2_auto_ds_0/Test_2_auto_ds_0.xci
# IP: The module: 'Test_2_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test_2/ip/Test_2_auto_ds_0/Test_2_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_2_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test_2/ip/Test_2_auto_ds_0/Test_2_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_2_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
