# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.srcs/sources_1/bd/dma/ip/dma_axi_smc_2/dma_axi_smc_2.xci
# IP: The module: 'dma_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/bd_1e2c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_0/bd_1e2c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_1/bd_1e2c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_2/bd_1e2c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_3/bd_1e2c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_4/bd_1e2c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_5/bd_1e2c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_6/bd_1e2c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_7/bd_1e2c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_8/bd_1e2c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_9/bd_1e2c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_10/bd_1e2c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_1/bd_1e2c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_1/bd_1e2c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_5/bd_1e2c_s00a2s_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_6/bd_1e2c_sawn_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_6/bd_1e2c_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_7/bd_1e2c_swn_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_7/bd_1e2c_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_8/bd_1e2c_sbn_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_8/bd_1e2c_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_9/bd_1e2c_m00s2a_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_smc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.srcs/sources_1/bd/dma/ip/dma_axi_smc_2/dma_axi_smc_2.xci
# IP: The module: 'dma_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/bd_1e2c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_0/bd_1e2c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_1/bd_1e2c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_2/bd_1e2c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_3/bd_1e2c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_4/bd_1e2c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_5/bd_1e2c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_6/bd_1e2c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_7/bd_1e2c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_8/bd_1e2c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_9/bd_1e2c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_10/bd_1e2c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_1/bd_1e2c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_1/bd_1e2c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_5/bd_1e2c_s00a2s_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_6/bd_1e2c_sawn_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_6/bd_1e2c_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_7/bd_1e2c_swn_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_7/bd_1e2c_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_8/bd_1e2c_sbn_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_8/bd_1e2c_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/bd_0/ip/ip_9/bd_1e2c_m00s2a_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
