# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gpio.xdc

# Block Designs: bd/Test_1/Test_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1 || ORIG_REF_NAME==Test_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_DataBufferAxi_0_1/Test_1_DataBufferAxi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_DataBufferAxi_0_1 || ORIG_REF_NAME==Test_1_DataBufferAxi_0_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_al_ultra96v2_0_1/Test_1_al_ultra96v2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_al_ultra96v2_0_1 || ORIG_REF_NAME==Test_1_al_ultra96v2_0_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_0_1/Test_1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_0_1 || ORIG_REF_NAME==Test_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_1_1/Test_1_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_1_1 || ORIG_REF_NAME==Test_1_axi_gpio_1_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_2_1/Test_1_axi_gpio_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_2_1 || ORIG_REF_NAME==Test_1_axi_gpio_2_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_3_1/Test_1_axi_gpio_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_3_1 || ORIG_REF_NAME==Test_1_axi_gpio_3_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_4_1/Test_1_axi_gpio_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_4_1 || ORIG_REF_NAME==Test_1_axi_gpio_4_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_5_1/Test_1_axi_gpio_5_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_5_1 || ORIG_REF_NAME==Test_1_axi_gpio_5_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_axi_gpio_6_1/Test_1_axi_gpio_6_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_axi_gpio_6_1 || ORIG_REF_NAME==Test_1_axi_gpio_6_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_xbar_1/Test_1_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_xbar_1 || ORIG_REF_NAME==Test_1_xbar_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_auto_ds_0/Test_1_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_auto_ds_0 || ORIG_REF_NAME==Test_1_auto_ds_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_auto_pc_0/Test_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_auto_pc_0 || ORIG_REF_NAME==Test_1_auto_pc_0} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_auto_ds_1/Test_1_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_auto_ds_1 || ORIG_REF_NAME==Test_1_auto_ds_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_auto_pc_1/Test_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_auto_pc_1 || ORIG_REF_NAME==Test_1_auto_pc_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_ps8_0_axi_periph_1/Test_1_ps8_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_ps8_0_axi_periph_1 || ORIG_REF_NAME==Test_1_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_pulse_generator_0_1/Test_1_pulse_generator_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_pulse_generator_0_1 || ORIG_REF_NAME==Test_1_pulse_generator_0_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_rst_ps8_0_99M_1/Test_1_rst_ps8_0_99M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_rst_ps8_0_99M_1 || ORIG_REF_NAME==Test_1_rst_ps8_0_99M_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_xlconstant_0_1/Test_1_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_xlconstant_0_1 || ORIG_REF_NAME==Test_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_xlconstant_1_1/Test_1_xlconstant_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_xlconstant_1_1 || ORIG_REF_NAME==Test_1_xlconstant_1_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_xlconstant_2_1/Test_1_xlconstant_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_xlconstant_2_1 || ORIG_REF_NAME==Test_1_xlconstant_2_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_xlconstant_3_1/Test_1_xlconstant_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_xlconstant_3_1 || ORIG_REF_NAME==Test_1_xlconstant_3_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_zynq_ultra_ps_e_0_1/Test_1_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==Test_1_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/Test_1/ip/Test_1_ila_0_1/Test_1_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_1_ila_0_1 || ORIG_REF_NAME==Test_1_ila_0_1} -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test_1/Test_1_ooc.xdc
