# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.runs/synth_1/Test_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.cache/wt [current_project]
set_property parent.project_path C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kv260_som:part0:1.4 [current_project]
set_property ip_output_repo c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/hdl/Test_wrapper.v
add_files C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.srcs/sources_1/bd/Test/Test.bd
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_0_4/Test_axi_gpio_0_4_board.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_0_4/Test_axi_gpio_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_0_4/Test_axi_gpio_0_4.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_1_2/Test_axi_gpio_1_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_1_2/Test_axi_gpio_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_1_2/Test_axi_gpio_1_2.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_2_2/Test_axi_gpio_2_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_2_2/Test_axi_gpio_2_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_2_2/Test_axi_gpio_2_2.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_3_2/Test_axi_gpio_3_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_3_2/Test_axi_gpio_3_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_3_2/Test_axi_gpio_3_2.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_4_2/Test_axi_gpio_4_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_4_2/Test_axi_gpio_4_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_4_2/Test_axi_gpio_4_2.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_5_2/Test_axi_gpio_5_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_5_2/Test_axi_gpio_5_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_5_2/Test_axi_gpio_5_2.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_6_2/Test_axi_gpio_6_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_6_2/Test_axi_gpio_6_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_axi_gpio_6_2/Test_axi_gpio_6_2.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_xbar_2/Test_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_rst_ps8_0_99M_4/Test_rst_ps8_0_99M_4_board.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_rst_ps8_0_99M_4/Test_rst_ps8_0_99M_4.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_rst_ps8_0_99M_4/Test_rst_ps8_0_99M_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_zynq_ultra_ps_e_0_4/Test_zynq_ultra_ps_e_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_zynq_ultra_ps_e_0_4/Test_zynq_ultra_ps_e_0_4.xdc]
set_property used_in_synthesis false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_auto_ds_2/Test_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_auto_ds_2/Test_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_auto_ds_2/Test_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_auto_pc_2/Test_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_auto_ds_3/Test_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_auto_ds_3/Test_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_auto_ds_3/Test_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/ip/Test_auto_pc_3/Test_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test/Test_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.srcs/constrs_1/new/gpio.xdc
set_property used_in_implementation false [get_files C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.srcs/constrs_1/new/gpio.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.srcs/utils_1/imports/synth_1/gpio_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Test_wrapper -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Test_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Test_wrapper_utilization_synth.rpt -pb Test_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
