# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.srcs/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/Data_Mobility_smartconnect_0_0.xci
# IP: The module: 'Data_Mobility_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/bd_f37a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_0/bd_f37a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_1/bd_f37a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_2/bd_f37a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_3/bd_f37a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_4/bd_f37a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_5/bd_f37a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_6/bd_f37a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_7/bd_f37a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_8/bd_f37a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_9/bd_f37a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_10/bd_f37a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_11/bd_f37a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_12/bd_f37a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_13/bd_f37a_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_14/bd_f37a_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_15/bd_f37a_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_16/bd_f37a_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_17/bd_f37a_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_18/bd_f37a_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_19/bd_f37a_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_20/bd_f37a_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_21/bd_f37a_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_22/bd_f37a_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_23/bd_f37a_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_24/bd_f37a_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_25/bd_f37a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_26/bd_f37a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_27/bd_f37a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_28/bd_f37a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_1/bd_f37a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_1/bd_f37a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_2/bd_f37a_arsw_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_3/bd_f37a_rsw_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_4/bd_f37a_awsw_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_5/bd_f37a_wsw_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_6/bd_f37a_bsw_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_10/bd_f37a_s00a2s_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_11/bd_f37a_sarn_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_11/bd_f37a_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_12/bd_f37a_srn_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_12/bd_f37a_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_16/bd_f37a_s01a2s_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_17/bd_f37a_sarn_1_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_17/bd_f37a_sarn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_18/bd_f37a_srn_1_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_18/bd_f37a_srn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_22/bd_f37a_s02a2s_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_23/bd_f37a_sarn_2_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_23/bd_f37a_sarn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_24/bd_f37a_srn_2_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_24/bd_f37a_srn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_25/bd_f37a_m00s2a_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_26/bd_f37a_m00arn_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_26/bd_f37a_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_27/bd_f37a_m00rn_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_27/bd_f37a_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mobility_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mobility_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.srcs/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/Data_Mobility_smartconnect_0_0.xci
# IP: The module: 'Data_Mobility_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/bd_f37a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_0/bd_f37a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_1/bd_f37a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_2/bd_f37a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_3/bd_f37a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_4/bd_f37a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_5/bd_f37a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_6/bd_f37a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_7/bd_f37a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_8/bd_f37a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_9/bd_f37a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_10/bd_f37a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_11/bd_f37a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_12/bd_f37a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_13/bd_f37a_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_14/bd_f37a_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_15/bd_f37a_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_16/bd_f37a_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_17/bd_f37a_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_18/bd_f37a_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_19/bd_f37a_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_20/bd_f37a_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_21/bd_f37a_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_22/bd_f37a_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_23/bd_f37a_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_24/bd_f37a_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_25/bd_f37a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_26/bd_f37a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_27/bd_f37a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_28/bd_f37a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_1/bd_f37a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_1/bd_f37a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_2/bd_f37a_arsw_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_3/bd_f37a_rsw_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_4/bd_f37a_awsw_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_5/bd_f37a_wsw_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_6/bd_f37a_bsw_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_10/bd_f37a_s00a2s_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_11/bd_f37a_sarn_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_11/bd_f37a_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_12/bd_f37a_srn_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_12/bd_f37a_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_16/bd_f37a_s01a2s_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_17/bd_f37a_sarn_1_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_17/bd_f37a_sarn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_18/bd_f37a_srn_1_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_18/bd_f37a_srn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_22/bd_f37a_s02a2s_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_23/bd_f37a_sarn_2_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_23/bd_f37a_sarn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_24/bd_f37a_srn_2_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_24/bd_f37a_srn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_25/bd_f37a_m00s2a_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_26/bd_f37a_m00arn_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_26/bd_f37a_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_27/bd_f37a_m00rn_0_ooc.xdc

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/bd_0/ip/ip_27/bd_f37a_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mobility_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mobility_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
