# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.srcs/sources_1/bd/Test_2/ip/Test_2_axi_dma_3_1/Test_2_axi_dma_3_1.xci
# IP: The module: 'Test_2_axi_dma_3_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test_2/ip/Test_2_axi_dma_3_1/Test_2_axi_dma_3_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_2_axi_dma_3_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test_2/ip/Test_2_axi_dma_3_1/Test_2_axi_dma_3_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_2_axi_dma_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test_2/ip/Test_2_axi_dma_3_1/Test_2_axi_dma_3_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_2_axi_dma_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.srcs/sources_1/bd/Test_2/ip/Test_2_axi_dma_3_1/Test_2_axi_dma_3_1.xci
# IP: The module: 'Test_2_axi_dma_3_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test_2/ip/Test_2_axi_dma_3_1/Test_2_axi_dma_3_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_2_axi_dma_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test_2/ip/Test_2_axi_dma_3_1/Test_2_axi_dma_3_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_2_axi_dma_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/Documents/GitHub/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Data_Mobility/Data_Mobility.gen/sources_1/bd/Test_2/ip/Test_2_axi_dma_3_1/Test_2_axi_dma_3_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_2_axi_dma_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
