# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.srcs/sources_1/bd/dma/ip/dma_axi_dma_0_1/dma_axi_dma_0_1.xci
# IP: The module: 'dma_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_dma_0_1/dma_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_dma_0_1/dma_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_dma_0_1/dma_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.srcs/sources_1/bd/dma/ip/dma_axi_dma_0_1/dma_axi_dma_0_1.xci
# IP: The module: 'dma_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_dma_0_1/dma_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_dma_0_1/dma_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_dma_0_1/dma_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
