# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.srcs/sources_1/bd/Data_Mobility/ip/Data_Mobility_wdata_reg_0/Data_Mobility_wdata_reg_0.xci
# IP: The module: 'Data_Mobility_wdata_reg_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_wdata_reg_0/Data_Mobility_wdata_reg_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mobility_wdata_reg_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_wdata_reg_0/Data_Mobility_wdata_reg_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mobility_wdata_reg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_wdata_reg_0/Data_Mobility_wdata_reg_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mobility_wdata_reg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.srcs/sources_1/bd/Data_Mobility/ip/Data_Mobility_wdata_reg_0/Data_Mobility_wdata_reg_0.xci
# IP: The module: 'Data_Mobility_wdata_reg_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_wdata_reg_0/Data_Mobility_wdata_reg_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mobility_wdata_reg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_wdata_reg_0/Data_Mobility_wdata_reg_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mobility_wdata_reg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Data_Mobility/ip/Data_Mobility_wdata_reg_0/Data_Mobility_wdata_reg_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_Mobility_wdata_reg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
