# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.srcs/sources_1/bd/dma/ip/dma_axi_smc_1_0/dma_axi_smc_1_0.xci
# IP: The module: 'dma_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/bd_2c55.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_0/bd_2c55_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_1/bd_2c55_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_2/bd_2c55_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_3/bd_2c55_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_4/bd_2c55_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_5/bd_2c55_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_6/bd_2c55_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_7/bd_2c55_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_8/bd_2c55_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_9/bd_2c55_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_1/bd_2c55_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_1/bd_2c55_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_5/bd_2c55_s00a2s_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_6/bd_2c55_sarn_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_6/bd_2c55_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_7/bd_2c55_srn_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_7/bd_2c55_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_8/bd_2c55_m00s2a_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.srcs/sources_1/bd/dma/ip/dma_axi_smc_1_0/dma_axi_smc_1_0.xci
# IP: The module: 'dma_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/bd_2c55.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_0/bd_2c55_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_1/bd_2c55_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_2/bd_2c55_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_3/bd_2c55_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_4/bd_2c55_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_5/bd_2c55_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_6/bd_2c55_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_7/bd_2c55_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_8/bd_2c55_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_9/bd_2c55_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_1/bd_2c55_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_1/bd_2c55_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_5/bd_2c55_s00a2s_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_6/bd_2c55_sarn_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_6/bd_2c55_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_7/bd_2c55_srn_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_7/bd_2c55_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/bd_0/ip/ip_8/bd_2c55_m00s2a_0_ooc.xdc

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ADMIN/OneDrive/GitHub/FPGA/Data_Mobility/Data_Mobility.gen/sources_1/bd/dma/ip/dma_axi_smc_1_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
