# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.srcs/sources_1/bd/Test_1/ip/Test_1_xbar_0/Test_1_xbar_0.xci
# IP: The module: 'Test_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Test_1/ip/Test_1_xbar_0/Test_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.srcs/sources_1/bd/Test_1/ip/Test_1_xbar_0/Test_1_xbar_0.xci
# IP: The module: 'Test_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Data-Mobility-Optimization-ML-IoT/Hardware/Vivado/Debug/Debug/Debug.gen/sources_1/bd/Test_1/ip/Test_1_xbar_0/Test_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
